%%  Sau MATLAB Colony Analyzer Toolkit
%
%%  LIGap_p.m

%   Author: Saurin Parikh, February 2019
%   dr.saurin.parikh@gmail.com

%   Linear Interpolation to predict plate background while introducing gaps
%   in the reference grid.
%
%   up : 0,1,2 : random gaps, upscale pattern gaps, random 96 source gaps
%
%   Part of LIEval.

%%

    function [data_fit, pos_miss] = LIGap_p(hours,n_plates,p2c_info,cont_name,...
        tablename_p2o,tablename_jpeg,pos_border,ss,IL,up)
    
        connectSQL;
        ss = ss/2;
        
        cont384 = 384*3+1:384*4;
        [nine61,nine62,nine63,nine64] = downscale(col2grid(cont384));
        nine6 = {nine61,nine62,nine63,nine64};
%         tmp96 = nine6{randi(4)};
        tmp96 = nine6{2};
        
        pos_reps = [110000,120000,130000,140000,...
            210000,220000,230000,240000];
        
        for ii = 1:length(hours)
            temp = [];
            for iii = 1:length(n_plates.x6144plate)

                pos.all = fetch(conn, sprintf(['select a.pos ',...
                    'from %s a ',...
                    'where %s = %d ',...
                    'order by %s, %s'],...
                    p2c_info(1,:),...
                    p2c_info(2,:),...
                    n_plates.x6144plate(iii),...
                    p2c_info(3,:),...
                    p2c_info(4,:)));

                pos.cont = fetch(conn, sprintf(['select a.pos ',...
                    'from %s a, %s b ',...
                    'where a.pos = b.pos and %s = %d and a.orf_name = ''%s'' ',...
                    'order by %s, %s'],...
                    tablename_p2o,...
                    p2c_info(1,:),...
                    p2c_info(2,:),...
                    n_plates.x6144plate(iii),...
                    cont_name,...
                    p2c_info(3,:),...
                    p2c_info(4,:)));

                avg_data = fetch(conn, sprintf(['select a.pos, a.hours, a.average ',...
                    'from %s a, %s b ',...
                    'where a.pos = b.pos and hours = %d and %s = %d ',...
                    'order by %s, %s'],...
                    tablename_jpeg,...
                    p2c_info(1,:),...
                    hours(ii),...
                    p2c_info(2,:),...
                    n_plates.x6144plate(iii),...
                    p2c_info(3,:),...
                    p2c_info(4,:)));
                
                all6144 = fetch(conn, sprintf(['select a.pos ',...
                    'from PT2_pos2orf_name a, PT2_pos2coor6144 b ',...
                    'where a.pos = b.pos and 6144plate = %d ',...
                    'order by 6144plate, 6144col, 6144row'],iii));
                cont6144 = fetch(conn, sprintf(['select a.pos ',...
                    'from PT2_pos2orf_name a, PT2_pos2coor6144 b ',...
                    'where a.pos = b.pos and 6144plate = %d ',...
                    'and a.orf_name = ''BF_control'' ',...
                    'order by 6144plate, 6144col, 6144row'],iii));

        %%  INTRODUCE GAPS
        
                if up == 0
                    if iii == 1
                        [pos_miss, p] = datasample(pos.cont.pos(~ismember(pos.cont.pos, pos_border.pos)),...
                            ss,'Replace',false);
                    else
                        pos_miss = pos.cont.pos(p);
                    end
                    pos_cont = pos.cont.pos(~ismember(pos.cont.pos,pos_miss));
                    cont_pos = col2grid(ismember(pos.all.pos, pos_cont));
                elseif up == 1          
                    if iii == 1
                        [tmp, p] = datasample(cont384, ss/4, 'Replace', false);
                        pos_miss = pos_reps + tmp;
                    else
                        pos_miss = pos_reps + cont384(p);
                    end
                    pos_cont = cont6144.pos(~ismember(cont6144.pos, pos_miss));
                    cont_pos = col2grid(ismember(all6144.pos, pos_cont));
                else
                    pos_miss = pos_reps + tmp96;
                    pos_cont = cont6144.pos(~ismember(cont6144.pos, pos_miss));
                    cont_pos = col2grid(ismember(all6144.pos, pos_cont));
                end

                cont_avg = col2grid(avg_data.average).*cont_pos;

        %%  CALCULATE BACKGROUND
        
                cont_avg(cont_avg == 0) = NaN;
                [a,b,c,d] = downscale(cont_avg);
                plates = {a,b,c,d};

                bground = LIHeart(plates,IL);
                
                bg{iii} = grid2row(plategen(bground{1},bground{2},bground{3},bground{4}))';%.*nonzero)';
                bg{iii}(bg{iii} == 0) = NaN;
                temp = abs([temp; [pos.all.pos, ones(length(pos.all.pos),1)*hours(ii),...
                    bg{iii}, avg_data.average, avg_data.average./bg{iii}]]);
                
            end
            data_fit{ii} = temp;
        end
    end